# aicore-pipeline.yaml

# Argo WorkflowTemplate for SAP AI Core
#
# - Pulls a custom Docker image with all dependencies pre-installed
# - Runs python /app/src/main.py inside the container
# - Designed for scalable, reproducible execution in SAP AI Core
#
# Usage:
#   1. Update the image: field with your Docker image name
#   2. Upload this YAML to SAP AI Core
#   3. Trigger the workflow via SAP AI Core UI or CLI

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: aicore-pipeline
  annotations:
    scenarios.ai.sap.com/description: "aicore docker"
    scenarios.ai.sap.com/name: "aicore-pipeline"
    executables.ai.sap.com/description: "aicore docker"
    executables.ai.sap.com/name: "aicore-pipeline"
  labels:
    scenarios.ai.sap.com/id: "aicore-pipeline"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: sriramrokkam
  entrypoint: aicore-pipeline
  templates:
    - name: aicore-pipeline
      steps:
        - - name: mypredictor
            template: mycodeblock1

    - name: mycodeblock1
      container:
        image: docker.io/sriramrokkam/aicore:bertopic
        command: ["/bin/sh", "-c"]
        args:
          - "python /app/src/main.py"
