apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: aicore-pipeline
  annotations:
    scenarios.ai.sap.com/description: "aicore docker"
    scenarios.ai.sap.com/name: "aicore-pipeline"
    executables.ai.sap.com/description: "aicore docker"
    executables.ai.sap.com/name: "aicore-pipeline"
  labels:
    scenarios.ai.sap.com/id: "aicore-pipeline"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: sriramrokkam
  entrypoint: aicore-pipeline
  templates:
    - name: aicore-pipeline
      steps:
        - - name: mypredictor
            template: mycodeblock1

    - name: mycodeblock1
      container:
        image: docker.io/sriramrokkam/aicore:bertopic
        command: ["/bin/sh", "-c"]
        args:
          - "python /app/src/main.py"